(defun filter1 (p s) (cond ((null s)
                         s)
                         ((null (funcall p (car s))) (filter1 p (cdr s)))
                         (t (cons (car s) (filter1 p (cdr s))))))
(print (filter1 #'atom (list '(A B C) 'g '(h d) 'j)))